version: '3.5'

services:
  rtc_db:
    container_name: rtc_db
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bQ5UroNM9PqslBs}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-rtc_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: on-failure

  rtc_cache:
    container_name: rtc_cache
    image: redis:7.2-rc3-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    restart: on-failure

  rtc_search:
    container_name: rtc_search
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - "${ELASTIC_PORT:-9200}:9200"
    networks:
      - rtc_search_net
    restart: on-failure

  rtc_kabana:
    container_name: rtc_kabana
    depends_on:
      - rtc_search
    image: docker.elastic.co/kibana/kibana:8.9.1
    environment:
      - ELASTICSEARCH_HOSTS=http://rtc_search:9200
    ports:
      - "5601:5601"
    networks:
      - rtc_search_net
    restart: on-failure

networks:
  rtc_search_net:
    driver: bridge

